### ISSUE TITLE
Get Related Content on the Site Sidebar

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#1]
Let's get this done as soon as we can. Leave updates here.

**Comment by rschmidt9** [comment]
Eric, reply to that ladies email when you get the chance.

Until then we @TechKinect/owners need to go through and choose the best posts to feature. Make sure that if you feature a post that the title isn't linked to the source or else it will not work well.

**Comment by rschmidt9** [comment]
I saw a bunch of emails with nrealte, @ericpaulsen  What's the status with them?

**Comment by ericpaulsen** [comment]
So I tried to checkout the Javascript for squarespace that they had sent in the email, and I had to change our password because I had forgotten it. Despite me changing the password, I still couldn't get into our account. I think it takes a certain amount of time for new passwords to reset on their system. So I will try to get in there later today.

**Comment by rschmidt9** [comment]
Can you log-in now?
